### ISSUE TITLE
Installing the GNOME 3.16 runtime freezes while writing objects

### ISSUE THREAD

**Issue by iBeliever** [alexlarsson/xdg-app#34]
Following the directions from the [wiki](https://wiki.gnome.org/Projects/SandboxedApps), I ran:

    $ xdg-app --user add-repo --no-gpg-verify gnome http://209.132.179.91/repo/
    $ xdg-app --user install-runtime gnome org.gnome.Platform 3.16

The first command worked fine. The second one worked for a while, and downloaded the runtime successfully. Several times, it crashed with the message "error: Too many open files", so I ran it again and it continued just fine. Then it apparently locked up at this point:

    Writing objects: 2

I let it sit for a while and nothing happened. Does this have to do with the error I got, or is there a bug somewhere?

I jumped ahead and GEdit, and the command completed successfully. 

Not sure if it matters, but I'm trying this on Arch Linux with GNOME.

**Comment by alexlarsson** [comment]
This is some kind of race condition in the new delta support in ostree (see https://bugzilla.gnome.org/show_bug.cgi?id=721799).
It seems to be caused by recent commits, but is believed to be fixed with current master, in particular this commit:
https://git.gnome.org/browse/ostree/commit/?id=6d1de23f878611e9de6a9a20e2f02d818a60edb0

Did you have that in your ostree version?

**Comment by iBeliever** [comment]
Pulling the latest code from master from both OSTree and xdg-app fixed the freeze. Thanks for your help!
