### ISSUE TITLE
temp files in exports

### ISSUE THREAD

**Issue by matthiasclasen** [alexlarsson/xdg-app#51]
I noticed that we link to temp files for the rewritten desktop files:

$ ls -l ~/.local/share/xdg-app/exports/share/applications/org.gnome.Builder.desktop 
lrwxrwxrwx. 1 mclasen mclasen 176 Jan 23 02:13 /home/mclasen/.local/share/xdg-app/exports/share/applications/org.gnome.Builder.desktop -> ../../../app/org.gnome.Builder/x86_64/master/552d5b9b01bf30f3bc453b7b9fecf6aebe66a26ac4798b93351bb8d3841d2047/export/share/applications/tmp-xdg-app_install-app1000-0OUzmrVQ.tmp

At the same time, the original, unrewritten desktop file is left in the ../export/share/applications/ directory.

I guess we are missing an atomic rename after writing out the temp file ?

**Comment by matthiasclasen** [comment]
Same for dbus service files and other files that get rewritten for export.

**Comment by alexlarsson** [comment]
The idea is to put the rewritten file in the deploy dir rather than the exports dir and then add a link to it so that we can properly clean up a dangling link if the app is removed.
The tmp name looks pretty bad yes, but do we really want to replace the "real" file? Maybe you want to have a look at it? Probably not though... lets just rename over it!

**Comment by alexlarsson** [comment]
We're now removing over the tmpfile
