### ISSUE TITLE
Case-sensitive prefix lookup

### ISSUE THREAD

**Issue by vrutkovs** [alexlarsson/xdg-app#58]
```
** (xdg-app install-app:12792): WARNING **: Non-prefixed filename org.gnome.baobab.desktop in app org.gnome.Baobab, ignoring.
```
I guess we shouldn't be that strict about finding prefixed names, it only confuses users

**Comment by alexlarsson** [comment]
It should not confuse users really. No tested app should be released to users with such a wrongly named file.

The limitation is required in order to ensure there are no filename conflicts between different apps, and to ensure one app cannot override another. See:
https://mail.gnome.org/archives/gnome-os-list/2015-February/msg00009.html
