### ISSUE TITLE
Security checks for embedded libraries

### ISSUE THREAD

**Issue by jpakkane** [alexlarsson/xdg-app#81]
When doing an xdg-app, the developers will need to embed all dependencies that are not provided by the platform. This will lead to apps that have an embedded version of, say, OpenSSL that has a security hole. You would like to block these sorts of binaries from running but this is currently not possible. There is no way to know what external source a program has embedded.

The Meson build system has now proposed a dependency manifest format that would list all external dependencies and versions a given binary uses. It also has a way of generating those manifests automatically so the developer does not need to write one by hand. This would allow xdg-app to maintain a blacklist of unsafe software versions and block those binaries from running. Adding something like this to xdg-app would improve security.

The proposal can be found [here](http://nibblestew.blogspot.com/2015/08/proposal-for-dependency-security-scheme.html).

**Comment by alexlarsson** [comment]
In general I don't want to put specific requirements on how an app is built, because that increases the work needed to make an app. Also, I imagine currently existing technologies like package managers to play a large part in how many apps are constructed. For instance you may use debs or rpms in your workflow to create the app or runtime. You then already have a lot of dependencies and metadata which you don't want to duplicate.

Obviously, if you were using meson to bundle your external dependencies using these dependency files would make a lot of sense. You could ship them in your package in a pre-determined way (just like you'd ship the apps rpm db if you used that to build the app).
