### ISSUE TITLE
xdg-app commands could follow a more consistent naming

### ISSUE THREAD

**Issue by steko** [alexlarsson/xdg-app#96]
Hello! Happy New Year :tada: 

I understand that the main use case for xdg-app is going to be via a graphical interface such as the one @hughsie [showed a few weeks ago](https://blogs.gnome.org/hughsie/2015/12/23/gnome-software-and-xdg-app/) but, for now, every time I use it from the command line I end up asking myself why the command naming is not more consistent, or to be more clear, similar to e.g. git.

Current commands related to apps:
-  install-app
-  update-app
-  make-app-current
-  uninstall-app
-  list-apps

Alternative naming:

- app-install 
- app-update
- app-make-current
- app-uninstall
- app-list 

and so on...

The rationale is, I think, that in most cases I know I want to perform an action on a specific xdg-app object (a runtime, a repository, an app, a remote) and the specific action is logically derived from that.

I hope the explanation is clear enough, and obviously it's nothing more than a suggestion from a user's perspective.

**Comment by hughsie** [comment]
FWIW, I agree that app-$foo would be more intuitive. Alternatively, just remove the app and runtime variants, and just find the right thing -- it's unlikely we'd have a app with the same name as the runtime and vice-versa.

**Comment by alexlarsson** [comment]
I agree that it would probably be more intuitive. And in fact, we're already kinda doing this for the build-* family of commands. Although "build" is a verb, so it also fits with the "verbify-object" model (such as install-app), which makes sense from the point of view of reading the command (but not necessarily of remembering it).

Another alternative is to go full git with "xdg-app app install", although that increases implementation complexity for little gain (imho).

As for using the same command for both runtime and app, i dunno. It seems safer to properly separate the namespaces to avoid intentional naming conflicts (although i agree that accidental ones seem unlikely).

**Comment by alexlarsson** [comment]
And if we do this, we should keep (silently) accepting the old names.

**Comment by alexlarsson** [comment]
Another alternative is to use "install", "update", "list" etc be for apps, and then "runtime-install", etc for runtimes...

**Comment by alexlarsson** [comment]
Actually, only install is unsafe in this sense. Maybe we should use non-prefixed ops and require --runtime on install.

**Comment by alexlarsson** [comment]
I just pushed a restructuring of the commands, and the usage page.
We now just use install/update/uninstall and you can optionally limit to --app or --runtime, otherwise we'll just autodetect what you want.

Can you try it out and see if there are any issues with the new approach you can see?
